apiVersion: v1
kind: Pod
metadata:
  name: network-debugger
  labels:
    app: network-debugger
spec:
  containers:
  - name: network-debugger-container
    image: public.ecr.aws/docker/library/ubuntu:22.04
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && sleep infinity"]
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 0